# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b2c727bfb4b6aacd08660aacce10a16"
name = "address-validation"
handle = "address-validation-44"
application_url = "https://slideshow-rentals-leaves-parking.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_shipping"

[auth]
redirect_urls = [
  "https://slideshow-rentals-leaves-parking.trycloudflare.com/auth/callback",
  "https://slideshow-rentals-leaves-parking.trycloudflare.com/auth/shopify/callback",
  "https://slideshow-rentals-leaves-parking.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
