# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b2c727bfb4b6aacd08660aacce10a16"
name = "address-validation"
handle = "address-validation-44"
application_url = "https://zip.shopify.poststrata.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shipping,write_products"

[auth]
redirect_urls = [
  "https://zip.shopify.poststrata.com/auth/callback",
  "https://zip.shopify.poststrata.com/auth/shopify/callback",
  "https://zip.shopify.poststrata.com/api/auth/callback"
]

[app_proxy]
url = "https://zip.shopify.poststrata.com"
subpath = "address-validation"
prefix = "apps"

[pos]
embedded = false
